name: Release Packages
on: 
  workflow_dispatch: 
  push:
    branches: 
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
            # required
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.PRIVATE_KEY }}
      
      - name: git checkout, fetch & bot-user
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            token: ${{ steps.app-token.outputs.token }}
      - run: |
              git config --global user.name github-actions
              git config --global user.email github-actions@github.com
              echo "hello my friend It is working" > TEST.md  
              git add .
              git commit -m "add: readme"
              git push origin develop